#!/usr/bin/env python3
"""Prepare offline atlas from Twemoji v17.0.1 archive (requires Pillow)."""
import hashlib, io, pathlib, sys, tarfile
from PIL import Image
root = pathlib.Path(__file__).resolve().parent.parent
archive = pathlib.Path(sys.argv[1]).read_bytes()
assert hashlib.sha256(archive).hexdigest() == 'b0c98753fd19be3dd8aac0af46817f71677c830432539ca2db26924a2492ab59', 'Unexpected source archive'
with tarfile.open(fileobj=io.BytesIO(archive)) as source:
    members = sorted((m for m in source.getmembers() if '/assets/72x72/' in m.name and m.name.endswith('.png')), key=lambda m:m.name)
    tile, columns = 24, 64
    atlas = Image.new('RGBA', (tile*columns, tile*((len(members)+columns-1)//columns)))
    entries = {}
    for index, member in enumerate(members):
        image = Image.open(source.extractfile(member)).convert('RGBA').resize((22,22), Image.Resampling.LANCZOS)
        atlas.paste(image, ((index%columns)*tile+1, (index//columns)*tile+1))
        sequence = ''.join(chr(int(c,16)) for c in pathlib.Path(member.name).stem.split('-'))
        # Accept both explicit emoji presentation and Twemoji's omitted VS16.
        entries[sequence] = index
        if sequence.endswith("\u20e3"):
            entries[sequence[:-1]+"\ufe0f\u20e3"] = index
        entries[sequence.replace('\ufe0f','')] = index
        if '\u200d' not in sequence and not sequence.endswith('\ufe0f'):
            entries[sequence+'\ufe0f'] = index
    atlas.save(root/'assets/emoji/atlas.png', optimize=True)
    license = next(m for m in source.getmembers() if m.name.endswith('/LICENSE-GRAPHICS'))
    (root/'licenses/Twemoji.txt').write_bytes(source.extractfile(license).read())
    def literal(s):
        return '"'+''.join('\\x%02x'%b for b in s.encode())+'"'
    ordered = sorted(entries.items(), key=lambda item:item[0].encode())
    (root/'src/ui/emoji_catalog.hpp').write_text('// Generated by scripts/prepare-emoji.py; Twemoji 17.0.1.\n#pragma once\nnamespace ui::emoji {\nstruct Entry { const char* sequence; unsigned tile; };\ninline constexpr Entry catalog[] = {\n'+''.join('{%s,%d},\n'%(literal(s),i) for s,i in ordered)+'};\n}\n')
    print(f'{len(members)} emoji images; {len(entries)} sequence aliases; atlas {atlas.size}')
